analogdevicesinc/libad9361-iio

CMakeLists.txt
appveyor.yml
libad9361-iio.iss.cmakein

appveyor.yml: Add the InnoSetup file and create an installer for libad9361.
Signed-off-by: Alexandra Trifan <Alexandra.Trifan@analog.com>

Add Windows installer for libad9361

---

ad9361_design_taps.c
test/CMakeLists.txt
test/auto_rate_test_hw.c

This PR adds tests for the ad9361_set_bb_rate function and fixes #29 which was verified here https://github.com/analogdevicesinc/libad9361-iio/commit/b2e88caf562bfac2daa45f9040f7e9f861f5e99a .

Auto rate tests

---

.travis.yml
CI/travis/before_deploy
CI/travis/before_install_darwin
CI/travis/before_install_linux
CI/travis/deploy
CI/travis/lib.sh
CI/travis/make_darwin
CI/travis/make_linux

A lot of this is stuff copied from libiio & adapted.

build: first set of fixes for the Travis-CI build

---

ad9361_calculate_rf_clock_chain.c
test/gen_rates_test.c

This PR coincides with https://github.com/analogdevicesinc/linux/pull/306
Rate validation values have been updated and tests now cover full sample rate range.

Fix rate checks

---

CMakeLists.txt

Signed-off-by: Adrian Suciu <adrian.suciu@analog.com>

cmake: change build define LIBIIO_EXPORTS to LIBAD9361_EXPORTS

---

test/filter_designer_hw.c

Signed-off-by: Srikanth <srikanth.pagadarai@analog.com>

Minor fix to for loop for testing rates

---

CI/travis/before_install_linux

Fix Centos builds which have bad version of cmake

---

CMakeLists.txt
cmake/cmake_uninstall.cmake.in

Signed-off-by: Jeff Long <willcode4@gmail.com>
Closes https://github.com/analogdevicesinc/libad9361-iio/issues/67

cmake: add "uninstall" target

---

CI/travis/before_install_linux
CI/travis/make_linux
azure-pipelines.yml

- update build and artifact names according to libiio build
- update pipeline triggers
Signed-off-by: Raluca Chis <raluca.chis@analog.com>

CI: update azure-pipelines.yml file

---

azure-pipelines.yml

Signed-off-by: Raluca Chis <raluca.chis@analog.com>

CI:change os versions to match os version used on libiio

---

bindings/python/requirements_dev.txt
bindings/python/setup.py.cmakein

This should fix the ARM build issues

Update versions of python dependencies

---

bindings/python/README.md

Add readme for python bindings

---

CI/travis/before_install_linux
CI/travis/make_linux
azure-pipelines.yml
bindings/python/CMakeLists.txt
bindings/python/tasks.py

- make all commands sudo
- add python package deployment
- builds triggered by tags will deploy to PyPi
- builds triggered by master will deploy to TestPyPi
Signed-off-by: Raluca Chis <raluca.chis@analog.com>

CI: add python deployment

---

azure-pipelines.yml

Remove deprecated os versions from Azure builds.
Add Ubuntu-22.04.
Signed-off-by: Raluca Chis <raluca.chis@analog.com>

CI:update ci

---

.github/workflows/doc.yml
CI/travis/before_install_linux
CI/travis/ci-ubuntu.sh
bindings/python/doc/conf.py.in
bindings/python/requirements.txt
bindings/python/requirements_doc.txt

Switch theme to furo (like pyadi-iio) and add deployment of doc for releases and development builds

Doc updates

---

azure-pipelines.yml

CI:add tags on CI triggers

---

azure-pipelines.yml

Fix Ubuntu "Failed to fetch" error.

CI: fix fetch error

---

CI/travis/ci-debian.sh
azure-pipelines.yml

Add debian Bullseye build to Azure CI.

CI:add debian build

---

azure-pipelines.yml

For different branches of libad9361 are needed artifacts from specific branches of libiio to work.

Download artifacts from specific branch libad9361-iio-v0

---

azure-pipelines.yml

For different branches of libad9361 are needed artifacts from specific branches of libiio to work.

Download artifacts from specific branch master

---

azure-pipelines.yml

Add variable initialization for release branch case

azure-pipeline.yml: add downloadBranch for release branch case

---

azure-pipelines.yml

Add two commits from main branch so that the 2022_R2 branch to search for the artifacts of 2022_R2 from libiio

Add commits from main branch to 2022_R2

---

CI/travis/ci-linux.sh
azure-pipelines.yml

Add new build on Linux and MacOS

Add new builds for different operating systems

---

CI/travis/ci-linux.sh
azure-pipelines.yml

Add new build on Linux and MacOS

Add ci builds v0
