.gitignore
Newer versions of cmake seem to generate new build
artifacts.
This shows up at least with cmake version 3.7.2 (on Ubuntu 17.04).
Also, it should be a good idea to ignore generated libs
and .pc file.
Vim swap files are notorious for being added by accident.
Signed-off-by: Alexandru Ardelean <alex.ardelean@analog.com>
=> .gitignore: add cmake, build artifacts, and vim swap files

.travis.yml, README.md
This adds a bit of repo branding.
And also highlights the parts of the build that need some fixing.
Personally, I don't like `[DO-NOT-MERGE-YET]` and/or `[WIP]` tags in a PR title, but for this one, I need it to run the build against this repo, as some parts of the travis build-run are not that easy to test/validate in a branch build.
Signed-off-by: Alexandru Ardelean <alex.ardelean@analog.com>
=> build,travis: add build badges and fix build with travis

CI/travis/before_install_darwin, CI/travis/before_install_linux
Currently Precise builds fail with error:
```
The following packages have unmet dependencies:
libiio : Depends: libxml2 (>= 2.8.0~precise1) but 2.7.8.dfsg-5.1ubuntu4.17 is to be installed
E: Unable to correct problems, you have held broken packages.
```
After taking a closer look, it seems that the actual libiio version that
was pulled was 0.9 (which is the version in `latest_libiio-precise.deb`
and the libiio build would always deploy a file named
`master_latest_libiio-precise.deb` (which contains the latest build on
master).
=> CI/travis/before_install_linux: pull actual latest libiio

test/CMakeLists.txt
In certain conditions/linker configuration, libiio needs to be explicitly
be specified.
Otherwise underlinking won't work too well.
This seems to happen when building libad9361-iio with a different install
prefix.
And from the looks of it, in appveyor we also need to specify this for
stuff to link to tests.
=> test/CMakeLists.txt: specifically link libiio to tests

CMakeLists.txt, ad9361_multichip_sync.c
4.3BSD,  POSIX.1-2001. POSIX.1-2001  declares  this  function obsolete;
use nanosleep(2) instead.  POSIX.1-2008 removes the specification
of usleep().Replace deprecated usleep
This fixes issue #20
Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>
=> ad9361_multichip_sync: Switch to nanosleep to replace deprecated usleep

appveyor.yml
The old '2015.1.{build}' format is a bit confusing, because it gives the
impression that something is stuck in the past.
Change this to '{branch}.{build}'.
That way we don't need to care about date/time, since Appveyor will track
that anyway.
=> appveyor.yml: change versioning to '{branch}.{build}' format

CI/travis/make_darwin, CI/travis/make_linux, ad9361_calculate_rf_clock_chain.c, appveyor.yml
This PR enables testing for top level functions:
- ad9361_calculate_rf_clock_chain
- ad9361_calculate_rf_clock_chain_fdp
- ad9361_generate_fir_taps
Hardware specific tests are disabled unless the necessary hardware is attached. These functions include: 
- ad9361_set_bb_rate_custom_filter_auto
- ad9361_set_bb_rate_custom_filter_manual
Included are some fixes the tests found, primarily when compiling on Windows.
=> Enable tests on all platforms

ad9361_baseband_auto_rate.c
Rates < 2.08 MSPS require the decimation in the FIR filter.
Under some circumstances, the loaded filter fails to enable due to
constrains enforced by the driver. Check the number of supported
taps for the current rate, and if the loaded filter has more taps than
supported, lower the base-band rate.
Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>
=> ad9361_baseband_auto_rate: Fix low rate filter enable

CMakeLists.txt, ad9361.h, bindings/matlab/CMakeLists.txt, bindings/matlab/ad9361-wrapper.h, test/testLoadLibrary.m
This PR adds support for [loadlibrary](https://www.mathworks.com/help/matlab/ref/loadlibrary.html) in MATLAB, which is implemented in a similar way for libiio. This is a requirement for our upcoming system object support in MathWorks_tools.
=> MATLAB loadlibrary support

appveyor.yml, libad9361-iio.iss.cmakein
This PR updates appveyor to include the new MATLAB bindings header to the installer and built artifacts.
=> MATLAB appveyor updates

.travis.yml
This changeset syncs the build matrix with libiio's.
And also the deployment settings for OS X have bee copied from libiio.
=> build,travis: extend build matrix & release deployment

CMakeLists.txt, ad9361.h, ad9361_fmcomms5_phase_sync.c, test/CMakeLists.txt, test/fmcomms5_sync_test.c
This PR adds an FMComms5 phase synchronization feature which matches or outperforms results from the implementation built into IIO-Scope. There is still some remaining validation on the HDL and driver side but this functionality provides reproducible results.
The updated doc includes references to how this functionality works and some of the associated hardware limitations. Tests include smoke and phase performance tests when enabled with the correct external hardware.
Signed-off-by: Travis Collins <travis.collins@analog.com>
=> Add fmcomms5 phase sync feature including doc and test

.travis.yml
Support for Xcode 8 in libiio has been dropped.
This change updates the pipeline in libad9361-iio to remove Xcode 8 as
well.
=> build,.travis.yml: drop xcode 8 build

CI/travis/after_deploy
The build path here is towards building Scopy.
After `libad9361-iio` is done, this will also trigger `gr-iio`.
=> CI/travis/after_deploy: trigger `gr-iio` build when done

.travis.yml
Recently docker builds have been failing because they couldn't negotiate
the algo for the SSH connection when deploying.
This has already been failing on other builds in a similar fashion, and now
we need to extend this to CentOS & Bionic docker builds.
=> build,centos,bionic: add ssh-dss algo to EXTRA_SSH env-var

.travis.yml
Apparently, even though Travis-CI is moving to use Xenial (16.04) dockers,
some Trusty dockers are still lurking around and randomly being assigned to
builds.
For this repo in particular, Trusty seems to be allocated mostly.
Force Xenial, since that will be the next default docker image in a few
months. This fails because of `EXTRA_SSH=-oHostKeyAlgorithms=+ssh-dss`
where the build complains that:
```
sftp -oHostKeyAlgorithms=+ssh-dss [secure]@[secure]
command-line line 0: Bad protocol 2 host key algorithms '+ssh-dss'.
```
We could remove the EXTRA_SSH stuff in the build, but we'd get the error
that the EXTRA_SSH option is fixing.
So, just default to Xenial docker images (for docker builds), add a note
about it in the `.travis.yml` and change later. We will need to re-update
builds at some …
=> .travis.yml: force xenial for docker builds

CI/travis/before_install_darwin
Travis-CI OS X images have plenty of stuff installed. And they are updated
every now-n-then. Running `brew upgrade` can take too much on older images.
So, don't upgrade packages. Just use the ones installed.
=> ci,os-x: reduce build times by not upgrading

.travis.yml, CI/travis/after_deploy, CI/travis/before_deploy, CI/travis/before_install_darwin, CI/travis/before_install_linux, CI/travis/deploy, CI/travis/lib.sh, CI/travis/make_darwin, CI/travis/make_linux
The build here got a bit neglected.
1. Dropping build for Xcode 9.2 ; was dropped for libiio a while ago
2. Removed -x shell specifier; not needed for now
3. More importantly: move the triggering of next builds into separate stage same as https://github.com/analogdevicesinc/libiio/pull/417
=> ci,build: various updates

.gitignore, .travis.yml, CI/travis/before_install_linux
Add CentOS 8 & Ubuntu 20.04 docker builds via Travis-CI infrastructure.
Globalize EXTRA_SSH env var. It's now in all docker images.
Add build/ folder to .gitignore.
For CentOS 8 we need to enable some extra repos.
=> ci,travis: add CentOS 8 & Ubuntu 20.04 builds

test/auto_rate_test_hw.c, test/filter_designer_hw.c, test/fmcomms5_sync_test.c
This PR is designed to make the library testable with the hardware testing harness where URIs are parameterizable.
This branch has been running fine in the harness for ~2 weeks. 
=> Update HW test to use environmental variables

CI/travis/before_install_linux, CI/travis/make_darwin, CI/travis/make_linux, CMakeLists.txt, ad9361_calculate_rf_clock_chain.c, ad9361_design_taps.c, azure-pipelines.yml
Copied from the libiio repo.
Tweaked/updated build scripts.
Currently still using the old swdownload artifacts.
Will add Azure artifacts and Windows builds in the next commits.
=> ci,azure-pipelines: add initial yaml file

CI/build_win.ps1, CI/install_deps_win.ps1, CI/travis/before_install_darwin, CI/travis/before_install_linux, CI/travis/lib.sh, CI/travis/make_linux, azure-pipelines.yml
Matrix strategy adapted from Travis Collins' work on libiio with Azure Pipelines.
This reduces duplication of the same steps for Linux & Mac builds.
Added artifact publishing. These are pipeline artifacts.
Also, using libiio's artifacts for the build.
For now, we're picking up the latest artifact, but later we may add branch matching (by un-commenting the bits in the yaml file).
=> ci,azure-pipelines: use matrix strategy, and user artifacts from libiio's pipeline

CMakeLists.txt, bindings/python/setup.py.cmakein
=> Make library check for python optional

bindings/python/test/test_ad9361.py
=> Fix flags for FMComms5 python tests

azure-pipelines.yml
Remove builds for Ubuntu 18.04 which is deprecated from Azure.
=> CI update: remove builds with deprecated OS version

CI/travis/before_install_darwin
Add libserialport to macOS dependencies.
Without libserialport the `make test` command will fail because it will look for libserialport.0.dylib and not find it.
=> CI: add libserialport to macOS dependencies

azure-pipelines.yml
Two new branches were added on the repository, for this ones the pipeline also needs to be triggered when PRs are raised or commits are pushed.
=> azure_pipelines.yml: add next_stable and libad9361-iio-v0 as trigger

azure-pipelines.yml
Eliminate the trigger for master branch and also change the conditional variable for publish artifacts step.
=> Change variable for main branch

README.md, bindings/python/README.md, mainpage.dox
=> Update doc to reference requirement of libiio

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
Persons specified in **CODEOWNERS** file will be automatically added as reviewers, whenever new PRs are opened, depending on affected folder. In addition to Code Owners, other reviewers can be added to each PR. CODEOWNERS file can be different from one branch to another. All new PRs will require the approval of at least one code owner.
**PULL_REQUEST_TEMPLATE.md** will populate all new PR description field. Beside PR description, it contains a list of checkboxes, ensuring everyone follows the same guidelines and enforces best practices. Pull Request Template applies for PRs against all protected branches.
Both files got added in .github
=> Add CODEOWNERS and PULL_REQUEST_TEMPLATE files
